import React, {useState} from 'react';
import Head from "next/head";
import {useForm} from "react-hook-form";
import {useRouter} from "next/router";
import ModalComponent from "@/components/ModalComponent";

function Index(props) {

    const router = useRouter();

    const {
        register,
        handleSubmit,
        formState: {errors},
        reset
    } = useForm();

    const [modalIsOpen, setModalIsOpen] = useState(false);
    const openModal = () => {
        setModalIsOpen(true);
    };

    const closeModal = () => {
        setModalIsOpen(false);
        router.reload()
    };

    const onsubmit = (data) => {
        setModalIsOpen(true);
    }

    return (
        <>
            <Head>
                <title>Agencia de Viagems - Destino </title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div className="container-sm d-sm-flex flex-row mb-5 mt-5 justify-content-between ">

                    <div className="contato_info w-100  d-sm-flex flex-column justify-content-center  p-5">
                        <img className="w-100" src="/img/img_contato.png"/>
                    </div>

                    <div className="form d-sm-flex w-100 flex-column justify-content-center p-5 bg-light rounded-4">
                        <h1 className="text-secondary">Contate-nos</h1>
                        <input type="text"
                               id="nome"
                               placeholder="Digite seu nome"
                               className="p-2 w-100 mb-2 border rounded-2"
                               {...register("nome", {required: true})}
                        />
                        {errors?.nome?.type === "required" && (
                            <p className="text-danger fw-bold">Campo obrigátorio</p>
                        )}
                        <input type="text"
                               id="email"
                               placeholder="example@mail.com"
                               className="p-2 mb-2 w-100 border rounded-2"
                               {...register("email", {
                                   required: true
                               })}
                        />
                        {errors?.email?.type === "required" && (
                            <p className="text-danger fw-bold">Campo obrigátorio</p>
                        )}

                        <textarea id="mensagem"
                                  rows="5"
                                  placeholder="Dugite sua duvida ou mensagem"
                                  className="p-2 w-100 mb-2 border rounded-2"
                                  {...register("mensagem", {required: true})}
                        ></textarea>
                        {errors?.mensagem?.type === "required" && (
                            <p className="text-danger fw-bold">Campo obrigátorio</p>
                        )}

                        <button className="btn  btn-warning w-100 p-2" onClick={(event) => {
                            event.preventDefault();
                            handleSubmit(onsubmit)();
                        }}> ENVIAR MENSAGEM
                        </button>
                    </div>

                    <ModalComponent isOpen={modalIsOpen}>
                        <p> Sua mensagem foi envida com sucesso</p>
                        <div className="d-flex justify-content-end">
                            <button className="btn btn-success" onClick={closeModal}>OK</button>
                        </div>
                    </ModalComponent>

                </div>


            </main>


        </>
    );
}

export default Index;