import React, {useEffect, useState} from 'react';
import Carousel from "@/components/cards/Carousel";
import Head from "next/head";
import {getDataVoos} from "@/pages/api/getDataVoos";
import CardVooPromoImg from "@/components/cards/CardVooPromoImg";

function Index(props) {

    const [voos, setVoos] = useState([]);
    const [searchTerm, setSearchTerm] = useState('');

    useEffect(() => {
        const getData = async () => {
            try {
                const vooDados = await getDataVoos();
                setVoos(vooDados);
            } catch (error) {
                console.error("Erro ao buscar dados", error);
            }
        };

        getData();
    }, []);


    const handleSearchChange = (e) => {
        setSearchTerm(e.target.value);
    };

    const handleSubmit = async () => {

        if (searchTerm.trim() === '') {
            const vooDados = await getDataVoos();
            setVoos(vooDados);
        } else {
            const filteredVoos = voos.filter((voo) => {
                // Aqui você pode ajustar a lógica de filtragem conforme necessário
                const destinoLowerCase = voo.destino.toUpperCase();
                const searchTermLowerCase = searchTerm.toUpperCase();
                return destinoLowerCase.includes(searchTermLowerCase);
            });

            setVoos(filteredVoos);
        }
    };


    return (
        <>
            <Head>
                <title>Agencia de Viagems - Destino </title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <Carousel url1="/img/banner_promo_01.jpg"
                          url2="/img/banner_promo_02.jpg"
                          url3="/img/banner_promo_03.jpg"
                          url4="/img/banner_promo_04.jpg"
                />

                <div className="container d-sm-flex flex-column mb-3 bg-light p-4 mt-5 rounded-4">
                    <div className="bg-app p-5 rounded-4">

                        <h1 className=" text-light">
                            <img width="48" height="48" src="https://img.icons8.com/emoji/48/airplane-emoji.png"
                                 alt="airplane-emoji" className="me-2"/>
                            VOOS PROMOCIONAIS
                        </h1>
                        <div className="d-flex">
                            <input
                                className="form-control me-2"
                                type="search"
                                placeholder="Informe um distino"
                                aria-label="Search"
                                value={searchTerm}
                                onChange={handleSearchChange}
                            />
                            <button
                                className="btn btn-outline-warning"
                                type="submit"
                                onClick={(e) => {
                                    e.preventDefault();
                                    handleSubmit();
                                }}>
                                Buscar
                            </button>
                        </div>
                    </div>

                    <div className="container mt-5 d-sm-flex flex-wrap">
                        {voos && voos.length > 0 ? (
                            voos.filter(value => value.desconto <= 100 && value.desconto > 0).map(vooMap =>
                                <div key={vooMap.id} className="mb-5">
                                    <CardVooPromoImg voo={vooMap}/>
                                </div>
                            )

                        ) : (
                            <div className="d-flex flex-column justify-content-center align-items-center ">
                                <h3 className="text-body-secondary"> OPS! Nao temos nenhuma opção no momento</h3>
                                <img width="48" height="48" src="https://img.icons8.com/color/48/000000/happy--v1.png"
                                     alt="happy--v1"/>
                            </div>
                        )}

                    </div>
                </div>
            </main>
        </>)
        ;
}

export default Index;