import Head from "next/head";
import React, {useEffect, useState} from "react";
import {useRouter} from "next/router";
import {getDataVoos} from "@/pages/api/getDataVoos";
import CardVoos from "@/components/cards/CardVoos";

const Destinobanner = () => {

    const router = useRouter();
    const {destinobanner} = router.query;
    const [voosDestino, setVoosDestino] = useState([])
    const [voosFiltrados, setVoosFIltrados] = useState([])

    useEffect(() => {

        const getData = async () => {
            try {
                const voosDados = await getDataVoos();
                setVoosDestino(voosDados);

            } catch (e) {
                console.error("Dados nao encontrados", e)
            }
        }

        getData();

    }, []);


    useEffect(() => {
        // Realize a filtragem dentro do useEffect para garantir que ocorra após a atualização do estado
        const voosFilter = voosDestino.filter(value => value.destino === destinobanner);
        setVoosFIltrados(voosFilter);
    }, [voosDestino, destinobanner]);



    return (
        <>
            <Head>
                <title>Agencia de Viagems - Destinos</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div className="container mt-5">

                    {voosFiltrados && voosFiltrados.length > 0 ? (
                        voosFiltrados.map(vooMap =>
                            <div key={vooMap.id} className="ms-2 mb-5">
                                <CardVoos voo={vooMap}/>
                            </div>
                        )

                    ) : (
                            <div className="d-flex flex-column justify-content-center align-items-center ">
                                <h3 className="text-body-secondary"> OPS! Nao temos nenhuma opção no momento</h3>
                                <img width="48" height="48" src="https://img.icons8.com/color/48/000000/happy--v1.png"
                                     alt="happy--v1"/>
                            </div>
                    )}


                </div>
            </main>
        </>
    )
}
export default Destinobanner